#!/bin/sh
#
# makesrcdist - make a source distribution of TTF.
#
# Usage:
#
#   ./makesrcdist [--snapshot] VERSION
#

# Support "--snapshot" option...
if test "$1" == "--snapshot"; then
    shift
    snapshot=1
else
    snapshot=0
fi


# Get the release version...
if test $# != 1; then
    echo "Usage: ./makesrcdist [--snapshot] VERSION"
    exit 1
fi

version=$1


# Check that version number has been updated everywhere...
status=0

if test $(grep AC_INIT configure.ac | awk '{print $2}') != "[$version],"; then
    echo "Still need to update AC_INIT version in 'configure.ac'."
    status=1
fi

if test $(head -4 CHANGES.md | tail -1 | awk '{print $1}') != "v$version"; then
    echo "Still need to update CHANGES.md version number."
    status=1
fi
if test $(head -4 CHANGES.md | tail -1 | awk '{print $3}') = "YYYY-MM-DD"; then
    echo "Still need to update CHANGES.md release date."
    status=1
fi

if test $status = 1; then
    exit 1
fi


# Tag release...
if test $snapshot = 0; then
    echo "Creating tag v$version for release..."
    git tag -m "Tag $version" v$version
    git push origin v$version
fi


# Make and sign source archive...
echo Creating ttf-$version.tar.gz...
git archive --format tar --prefix=ttf-$version/ HEAD | gzip -v9 >ttf-$version.tar.gz
gpg --detach-sign ttf-$version.tar.gz
